version: '3.8'

services:

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./project/.env
    expose:
      - 5432

  web:
    build: ./project  # Указываем новый путь к контексту сборки
    volumes:
      - ./project:/project  # Обновляем путь монтирования для кода проекта
      - static:/project/static
    expose:
      - 8000
    env_file:
      - ./project/.env
    command: ["entrypoint/project.sh"]
    depends_on:
      - db

  nginx:
    restart: always
    image: nginx:1.23-alpine
    ports:
      - "80:80"
    volumes:
      - static:/var/www/html/static
      - ./nginx.d:/etc/nginx/conf.d
      - ./src:/usr/share/nginx/html
    depends_on:
      - web
  

volumes:
  postgres_data:
  static: