# Generated by Django 5.0 on 2023-12-15 15:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("hookah", "0001_initial"),
        ("owner", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="organization",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="owner.owner"
            ),
        ),
    ]
