# Generated by Django 4.2.7 on 2023-11-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_role",
            field=models.TextField(
                choices=[
                    ("UNKNOWN", "Unknown"),
                    ("OWNER", "Owner"),
                    ("ADMIN", "Admin"),
                    ("HOOKAH", "Hookah"),
                ],
                default="UNKNOWN",
            ),
        ),
    ]
