# Generated by Django 4.2 on 2024-01-20 15:37

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Generator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("main", models.CharField(max_length=30)),
                ("second", models.CharField(max_length=30)),
                ("tint", models.CharField(max_length=30)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
