# Generated by Django 4.2 on 2024-01-20 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tobacco",
            name="count",
        ),
        migrations.AddField(
            model_name="tobacco",
            name="weight",
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tobacco",
            name="best_before_date",
            field=models.DateTimeField(),
        ),
    ]
