# Generated by Django 4.2 on 2024-01-20 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0002_remove_tobacco_count_tobacco_weight_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tobacco",
            name="purchase_date",
            field=models.DateTimeField(default="2024-01-20T14:14:53.244Z"),
            preserve_default=False,
        ),
    ]
