# Generated by Django 4.2 on 2024-01-22 13:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("storage", "0003_tobacco_purchase_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="tobacco",
            name="created",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tobacco",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tobacco",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
